name: Running xk6-kubernetes
on: [push]

jobs:
  k6_local_test:
    name: k6 running pipeline xk6-kubernetes
    runs-on: ubuntu-latest
    container: docker://golang:1.19-alpine

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-kubernetes
        run: xk6 build --with github.com/grafana/xk6-kubernetes

      - name: Run xk6-kuberenetes with script
        run: ./k6 run --out json=teste-github.json script2.js

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: metrics-results
          path: teste-github.json
