name: Running xk6-kubernetes
on: [push]

jobs:
  k6_local_test:
    name: k6 running pipeline xk6-kubernetes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      
      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      
      - name: Install xk6
        run: go install go.k6.io/xk6/cmd/xk6@latest

      - name: Build xk6-kubernetes
        run: xk6 build --with github.com/grafana/xk6-kubernetes

      - name: install k8s
        run: |
          apt install curl
          curl -sfL https://get.k3s.io | K3S_KUBECONFIG_MODE=777 sh -
          cat /etc/rancher/k3s/k3s.yaml
          mkdir -p ~/.kube
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
      - name: example tests
        run: |
          kubectl cluster-info
          kubectl create namespace performance
      - name: Run xk6-kuberenetes with script
        run: ./k6 run --out json=teste-github.json script2.js

      - name: Archive code coverage results
        uses: actions/upload-artifact@v4
        with:
          name: metrics-results
          path: |
            teste-github.json
            *.html
          retention-days: 3d
